/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=tests/fixtures/consumer/wrangler.jsonc --config=wrangler.jsonc --include-runtime=false --env-interface=ConsumerEnv tests/fixtures/consumer/worker-configuration.d.ts` (hash: c172062a1ee56b6785038ecc6f859f46)
interface __BaseEnv_ConsumerEnv {
	AUTH: Service<typeof import("../../../worker/index").SessionValidation>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ConsumerEnv {}
}
interface ConsumerEnv extends __BaseEnv_ConsumerEnv {}
