import { DatabaseSync } from "node:sqlite";
import { getMigrations } from "better-auth/db/migration";
import { magicLink } from "better-auth/plugins";
import { writeFileSync } from "node:fs";
// Generate SQL only. Wrangler alone applies migrations. The only enabled plugin
// adds no schema. D1 application is verified separately in workerd tests.
const db = new DatabaseSync(":memory:");
const plan = await getMigrations({
  database: db,
  plugins: [
    magicLink({
      storeToken: "hashed",
      expiresIn: 900,
      sendMagicLink: () => Promise.resolve(),
    }),
  ],
});
writeFileSync(
  "migrations/0001_better_auth.sql",
  "-- Generated by Better Auth 1.7.3 getMigrations; reviewed, applied by Wrangler.\n" +
    (await plan.compileMigrations()) +
    "\n",
);
db.close();
